# Generated by Django 4.1.2 on 2022-10-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=20, primary_key=True, serialize=False
                    ),
                ),
                ("target_average_illumination", models.IntegerField()),
                ("sunrise", models.TimeField()),
                ("sunset", models.TimeField()),
                ("mode", models.IntegerField(choices=[(1, "Default")])),
            ],
        ),
    ]
