# Generated by Django 4.1.2 on 2022-11-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Decision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensor", models.CharField(db_index=True, max_length=20)),
                ("time", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("blind", models.FloatField()),
                ("light", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="DecisionMaker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
