# Generated by Django 4.1.2 on 2022-11-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DecisionMaker',
        ),
        migrations.AlterField(
            model_name='decision',
            name='time',
            field=models.DateTimeField(db_index=True),
        ),
    ]
