version: "3"
services:
  backend:
    container_name: lcs-server
    image: light-control-system
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - .:/code
    # depends_on:
    #   - redis
    ports:
      - "8000:8000"
  
  db:
    container_name: lcs-postgres
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'

  # redis:
  #   container_name: redis
  #   image: redis:alpine
  #   ports:
  #     - 6379:6379
  
  # django-q:
  #   container_name: django-q
  #   image: django-q
  #   environment:
  #     - POSTGRES_NAME=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   volumes:
  #     - .:/code
  #   depends_on:
  #     - redis

