# Generated by Django 4.1.2 on 2022-10-17 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_rename_lightintensitypoint_lightintensity_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LightIntensity",
            new_name="LightIntensityPoint",
        ),
    ]
