# Generated by Django 4.1.2 on 2022-10-23 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_rename_lightintensity_lightintensitypoint"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lightintensitypoint",
            old_name="time",
            new_name="datetime",
        ),
    ]
