# Generated by Django 4.1.2 on 2022-11-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_rename_time_lightintensitypoint_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lightintensitypoint',
            name='datetime',
            field=models.DateTimeField(db_index=True),
        ),
    ]
